# Generated by Django 4.2 on 2023-04-20 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='asstcoach',
            new_name='schedule',
        ),
        migrations.RemoveField(
            model_name='player',
            name='headcoach',
        ),
        migrations.RemoveField(
            model_name='player',
            name='league',
        ),
        migrations.RemoveField(
            model_name='player',
            name='sport',
        ),
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
    ]
