# Generated by Django 4.2 on 2023-04-20 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_asstcoach_player_schedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=75)),
                ('coach', models.CharField(max_length=75)),
                ('contact', models.CharField(max_length=75)),
                ('sports', models.CharField(choices=[('A', 'Baseball'), ('B', 'Basketball'), ('C', 'Football'), ('D', 'Soccer'), ('E', 'Tennis'), ('F', 'Golf')], default='A', max_length=1)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.player')),
            ],
        ),
    ]
