# Generated by Django 4.2 on 2023-04-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='sports',
            field=models.CharField(choices=[('A', 'Practice'), ('B', 'Game')], default='A', max_length=1),
        ),
    ]
