# Generated by Django 4.2 on 2023-04-20 19:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_sport_sports'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Game or Practice date'),
            preserve_default=False,
        ),
    ]
