# Generated by Django 4.2 on 2023-04-21 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_sport_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Game or Practice date')),
                ('event', models.CharField(choices=[('A', 'Practice'), ('B', 'Game')], default='A', max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='schedule',
        ),
        migrations.AddField(
            model_name='player',
            name='lifetime_ba',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Sport',
        ),
        migrations.AddField(
            model_name='schedule',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.player'),
        ),
    ]
